2025-04-19 06:21:25,128 : INFO : Start of Prediction
2025-04-19 06:21:25,129 : INFO : run_id:2025-04-19_062125_966359380
2025-04-19 06:21:25,129 : INFO : Start of Data Load, validation and transformation
2025-04-19 06:21:25,129 : INFO : Start of Archiving Old Rejected Files...
2025-04-19 06:21:25,132 : INFO : End of Archiving Old Rejected Files...
2025-04-19 06:21:25,132 : INFO : Start of Archiving Old Validated Files...
2025-04-19 06:21:25,137 : INFO : End of Archiving Old Validated Files...
2025-04-19 06:21:25,137 : INFO : Start of Archiving Old Processed Files...
2025-04-19 06:21:25,139 : INFO : End of Archiving Old Processed Files...
2025-04-19 06:21:25,139 : INFO : Start of Archiving Old Result Files...
2025-04-19 06:21:25,140 : INFO : End of Archiving Old Result Files...
2025-04-19 06:21:25,140 : INFO : Start of Reading values From Schema...
2025-04-19 06:21:25,140 : INFO : End of Reading values From Schema...
2025-04-19 06:21:25,141 : INFO : Start of Validating Column Length...
2025-04-19 06:21:25,174 : INFO : Invalid Columns Length :: hr_employee_churn_data.csv
2025-04-19 06:21:25,174 : INFO : End of Validating Column Length...
2025-04-19 06:21:25,174 : INFO : Start of Validating Missing Values...
2025-04-19 06:21:25,175 : INFO : End of Validating Missing Values...
2025-04-19 06:21:25,175 : INFO : Start of Replacing Missing Values with NULL...
2025-04-19 06:21:25,175 : INFO : End of Replacing Missing Values with NULL...
2025-04-19 06:21:25,176 : INFO : Start of Creating Table...
2025-04-19 06:21:25,177 : INFO : Opened prediction database successfully
2025-04-19 06:21:25,191 : INFO : CREATE TABLE prediction_raw_data_t column_name
2025-04-19 06:21:25,198 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,205 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,212 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,218 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,224 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,230 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,235 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,242 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:25,243 : INFO : End of Creating Table...
2025-04-19 06:21:25,246 : INFO : Opened prediction database successfully
2025-04-19 06:21:25,247 : INFO : Start of Inserting Data into Table...
2025-04-19 06:21:25,247 : INFO : End of Inserting Data into Table...
2025-04-19 06:21:25,247 : INFO : Start of Exporting Data into CSV...
2025-04-19 06:21:25,248 : INFO : Opened prediction database successfully
2025-04-19 06:21:25,251 : INFO : End of Exporting Data into CSV...
2025-04-19 06:21:25,251 : INFO : Start of Moving Processed Files...
2025-04-19 06:21:25,252 : INFO : End of Moving Processed Files...
2025-04-19 06:21:25,252 : INFO : End of Data Load, validation and transformation
2025-04-19 06:21:25,252 : INFO : Start of Preprocessing...
2025-04-19 06:21:25,252 : INFO : Start of reading dataset...
2025-04-19 06:21:25,256 : INFO : End of reading dataset...
2025-04-19 06:21:25,257 : INFO : Start of feature encoding...
2025-04-19 06:21:25,270 : INFO : End of feature encoding...
2025-04-19 06:21:25,271 : INFO : Start of Droping Columns...
2025-04-19 06:21:25,271 : INFO : End of Droping Columns...
2025-04-19 06:21:25,271 : INFO : Start of finding missing values...
2025-04-19 06:21:25,272 : INFO : End of finding missing values...
2025-04-19 06:21:25,272 : INFO : Start of building final predictset...
2025-04-19 06:21:25,275 : INFO : End of building final predictset...
2025-04-19 06:21:25,276 : INFO : End of Preprocessing...
2025-04-19 06:21:25,276 : INFO : Start of Load Model
2025-04-19 06:21:25,276 : ERROR : Exception raised while Loading Model: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
2025-04-19 06:21:25,277 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\prediction\predict_model.py", line 58, in batch_predict_from_model
    kmeans = self.fileOperation.load_model('KMeans')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 85, in load_model
    raise Exception()
Exception
