2025-04-19 06:19:40,635 : INFO : Start of Prediction
2025-04-19 06:19:40,636 : INFO : run_id:2025-04-19_061940_998979015
2025-04-19 06:19:40,637 : INFO : Start of Data Load, validation and transformation
2025-04-19 06:19:40,637 : INFO : Start of Archiving Old Rejected Files...
2025-04-19 06:19:40,638 : INFO : End of Archiving Old Rejected Files...
2025-04-19 06:19:40,638 : INFO : Start of Archiving Old Validated Files...
2025-04-19 06:19:40,639 : INFO : End of Archiving Old Validated Files...
2025-04-19 06:19:40,639 : INFO : Start of Archiving Old Processed Files...
2025-04-19 06:19:40,641 : INFO : End of Archiving Old Processed Files...
2025-04-19 06:19:40,641 : INFO : Start of Archiving Old Result Files...
2025-04-19 06:19:40,641 : INFO : End of Archiving Old Result Files...
2025-04-19 06:19:40,642 : INFO : Start of Reading values From Schema...
2025-04-19 06:19:40,642 : INFO : End of Reading values From Schema...
2025-04-19 06:19:40,643 : INFO : Start of Validating Column Length...
2025-04-19 06:19:40,695 : INFO : Invalid Columns Length :: HR_capstone_dataset.csv
2025-04-19 06:19:40,695 : INFO : End of Validating Column Length...
2025-04-19 06:19:40,695 : INFO : Start of Validating Missing Values...
2025-04-19 06:19:40,696 : INFO : End of Validating Missing Values...
2025-04-19 06:19:40,696 : INFO : Start of Replacing Missing Values with NULL...
2025-04-19 06:19:40,696 : INFO : End of Replacing Missing Values with NULL...
2025-04-19 06:19:40,696 : INFO : Start of Creating Table...
2025-04-19 06:19:40,698 : INFO : Opened prediction database successfully
2025-04-19 06:19:40,709 : INFO : CREATE TABLE prediction_raw_data_t column_name
2025-04-19 06:19:40,718 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,726 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,734 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,742 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,750 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,757 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,763 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,770 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:19:40,771 : INFO : End of Creating Table...
2025-04-19 06:19:40,775 : INFO : Opened prediction database successfully
2025-04-19 06:19:40,776 : INFO : Start of Inserting Data into Table...
2025-04-19 06:19:40,777 : INFO : End of Inserting Data into Table...
2025-04-19 06:19:40,777 : INFO : Start of Exporting Data into CSV...
2025-04-19 06:19:40,778 : INFO : Opened prediction database successfully
2025-04-19 06:19:40,781 : INFO : End of Exporting Data into CSV...
2025-04-19 06:19:40,782 : INFO : Start of Moving Processed Files...
2025-04-19 06:19:40,783 : INFO : End of Moving Processed Files...
2025-04-19 06:19:40,783 : INFO : End of Data Load, validation and transformation
2025-04-19 06:19:40,783 : INFO : Start of Preprocessing...
2025-04-19 06:19:40,783 : INFO : Start of reading dataset...
2025-04-19 06:19:41,471 : INFO : End of reading dataset...
2025-04-19 06:19:41,471 : INFO : Start of feature encoding...
2025-04-19 06:19:41,528 : INFO : End of feature encoding...
2025-04-19 06:19:41,529 : INFO : Start of Droping Columns...
2025-04-19 06:19:41,530 : INFO : End of Droping Columns...
2025-04-19 06:19:41,530 : INFO : Start of finding missing values...
2025-04-19 06:19:41,531 : INFO : End of finding missing values...
2025-04-19 06:19:41,531 : INFO : Start of building final predictset...
2025-04-19 06:19:41,538 : INFO : End of building final predictset...
2025-04-19 06:19:41,538 : INFO : End of Preprocessing...
2025-04-19 06:19:41,538 : INFO : Start of Load Model
2025-04-19 06:19:41,538 : ERROR : Exception raised while Loading Model: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
2025-04-19 06:19:41,541 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\prediction\predict_model.py", line 58, in batch_predict_from_model
    kmeans = self.fileOperation.load_model('KMeans')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 85, in load_model
    raise Exception()
Exception
